import { normalizeId } from '../types'
import type {
  PlanetMission,
} from '../types'
import { buildMissionList } from './mission-overrides'

const choices = (...labels: string[]): MissionChoice[] =>
  labels.map((label) => ({ id: normalizeId(label), label }))

const hotspots = (...items: Array<[id: string, label: string, clue: string, lat: number, lon: number, color: string]>): HotspotConfig[] =>
  items.map(([id, label, clue, lat, lon, color]) => ({ id, label, clue, lat, lon, color }))

export const DEFAULT_MISSIONS: PlanetMission[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    subtitle: 'World of molten dawns and frozen nights',
    prompt: 'Recover three thermal beacons hidden across Mercury’s battered day-night frontier.',
    question: 'Why does Mercury swing between extreme heat and cold?',
    answer: 'It barely has an atmosphere to trap heat',
    celebration: 'Thermal map restored. Mercury’s brutal rhythm is now readable.',
    choices: choices(
      'It barely has an atmosphere to trap heat',
      'Its rings block sunlight',
      'Its oceans freeze every night',
    ),
    hotspots: hotspots(
      ['caloris', 'Caloris Rim', 'Mercury is heavily cratered because its old surface preserves ancient impacts.', 14, 48, '#ffd4a5'],
      ['scarps', 'Sunrise Scarps', 'Gigantic cliffs formed as Mercury slowly shrank while cooling.', -18, -36, '#ffd7b5'],
      ['shadow', 'Shadow Basin', 'With almost no atmosphere, heat escapes fast once the Sun moves away.', 42, 162, '#ffefc7'],
    ),
    visualKind: 'mercury',
    radius: 1.15,
    orbitRadius: 11,
    orbitSpeed: 0.18,
    rotationSpeed: 0.17,
    focusDistance: 5.8,
    atmosphereColor: '#ffc8a8',
    glowColor: '#ff8c53',
    moonCount: 0,
    axialTilt: 0.04,
  },
  {
    id: 'venus',
    name: 'Venus',
    subtitle: 'A glowing pressure chamber hidden beneath sulfur clouds',
    prompt: 'Scan three storm beacons drifting through Venus’s blazing cloud deck.',
    question: 'What makes Venus even hotter than Mercury?',
    answer: 'Its dense atmosphere traps heat in a runaway greenhouse effect',
    celebration: 'Cloud resonance solved. Venus glows like a sealed furnace.',
    choices: choices(
      'Its dense atmosphere traps heat in a runaway greenhouse effect',
      'It is closer to Jupiter',
      'Its surface is made of hot ice',
    ),
    hotspots: hotspots(
      ['crown', 'Crown Vortex', 'Venus is wrapped in thick clouds made from sulfuric acid droplets.', 22, 18, '#ffd27a'],
      ['pressure', 'Pressure Bloom', 'The air pressure on Venus is crushing, far stronger than Earth’s.', -14, 124, '#ffe2a8'],
      ['glow', 'Infrared Veil', 'A runaway greenhouse effect keeps Venus hotter than Mercury.', 36, -78, '#fff0be'],
    ),
    visualKind: 'venus',
    radius: 1.4,
    orbitRadius: 15.4,
    orbitSpeed: 0.12,
    rotationSpeed: 0.07,
    focusDistance: 6.6,
    atmosphereColor: '#ffd18a',
    glowColor: '#ffbf4a',
    moonCount: 0,
    axialTilt: 0.05,
  },
  {
    id: 'earth',
    name: 'Earth',
    subtitle: 'Blue oceans, moonlight tides, and living weather',
    prompt: 'Lock onto three biosphere beacons across Earth’s oceans, auroras, and moonlit edge.',
    question: 'What makes Earth stand out from every other planet in this journey?',
    answer: 'It has stable liquid water on the surface',
    celebration: 'Orbital observatory synced. Earth shines as the living world of the route.',
    choices: choices(
      'It has stable liquid water on the surface',
      'It has the largest rings',
      'It is the hottest planet',
    ),
    hotspots: hotspots(
      ['aurora', 'Aurora Crown', 'Earth’s magnetic field channels charged particles into glowing auroras.', 64, -36, '#96f7ff'],
      ['ocean', 'Ocean Mirror', 'Most of Earth’s surface is covered by liquid water oceans.', -8, 68, '#8fe3ff'],
      ['tide', 'Tidal Arc', 'The Moon helps drive tides and stabilizes Earth’s long-term wobble.', 18, -144, '#dffaff'],
    ),
    visualKind: 'earth',
    radius: 1.55,
    orbitRadius: 21.2,
    orbitSpeed: 0.09,
    rotationSpeed: 0.22,
    focusDistance: 7.1,
    atmosphereColor: '#6fbcff',
    glowColor: '#33b4ff',
    moonCount: 1,
    moonScale: 0.32,
    moonOrbitRadius: 2.65,
    axialTilt: 0.42,
  },
  {
    id: 'mars',
    name: 'Mars',
    subtitle: 'Rust deserts carved by ancient water',
    prompt: 'Recover rover memory shards from canyons, dust plains, and frozen caps on Mars.',
    question: 'Which clue suggests Mars once had flowing water?',
    answer: 'Dry river valleys and delta-like landforms',
    celebration: 'Rover archive restored. Mars keeps the memory of vanished rivers.',
    choices: choices(
      'Dry river valleys and delta-like landforms',
      'Bright planetary rings',
      'A deep blue global ocean today',
    ),
    hotspots: hotspots(
      ['valles', 'Valles Signal', 'Mars hosts enormous canyons and channels carved into old crust.', -12, -66, '#ffbf8b'],
      ['delta', 'Delta Cache', 'Scientists have found fan-shaped deposits that look like ancient river deltas.', 24, 44, '#ff9c68'],
      ['caps', 'Polar Vault', 'Frozen water and carbon dioxide still sit in Mars’s polar caps.', 70, 110, '#ffe8d9'],
    ),
    visualKind: 'mars',
    radius: 1.25,
    orbitRadius: 27.1,
    orbitSpeed: 0.068,
    rotationSpeed: 0.19,
    focusDistance: 6.1,
    atmosphereColor: '#ffb48e',
    glowColor: '#ff6a3d',
    moonCount: 2,
    moonScale: 0.16,
    moonOrbitRadius: 1.95,
    axialTilt: 0.44,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    subtitle: 'Storm bands wrapped around a giant of gravity',
    prompt: 'Thread the magnetosphere and find three signal flares across Jupiter’s belts and moons.',
    question: 'What is Jupiter’s Great Red Spot?',
    answer: 'A giant long-lived storm larger than Earth',
    celebration: 'Storm lattice mapped. Jupiter roars like a living atmosphere.',
    choices: choices(
      'A giant long-lived storm larger than Earth',
      'A volcano on the surface',
      'A red ocean hidden below the clouds',
    ),
    hotspots: hotspots(
      ['storm', 'Red Spot Beacon', 'The Great Red Spot is a colossal storm that has lasted for centuries.', -18, 32, '#ffae92'],
      ['bands', 'Jetstream Bands', 'Jupiter’s atmosphere forms powerful bright and dark cloud belts.', 26, -124, '#ffe0a8'],
      ['moons', 'Moon Choir', 'Jupiter’s big moons are worlds of their own, including icy Europa and volcanic Io.', 54, 122, '#fff0d6'],
    ),
    visualKind: 'jupiter',
    radius: 3.6,
    orbitRadius: 39.4,
    orbitSpeed: 0.036,
    rotationSpeed: 0.32,
    focusDistance: 11.5,
    atmosphereColor: '#ffd4a8',
    glowColor: '#ff9460',
    moonCount: 4,
    moonScale: 0.18,
    moonOrbitRadius: 4.8,
    axialTilt: 0.08,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    subtitle: 'A ringed cathedral of ice and light',
    prompt: 'Tune three harmonic beacons hidden in Saturn’s bands and shimmering rings.',
    question: 'What are Saturn’s rings mostly made of?',
    answer: 'Countless pieces of ice and rock',
    celebration: 'Ring harmonics stabilized. Saturn’s halo now sings in phase.',
    choices: choices(
      'Countless pieces of ice and rock',
      'Liquid fire',
      'Solid metal plates',
    ),
    hotspots: hotspots(
      ['rings', 'Ring Choir', 'Saturn’s rings are made from vast numbers of icy particles mixed with rocky debris.', 10, 86, '#ffe8ba'],
      ['gap', 'Cassini Gap', 'The rings are divided into bands and gaps shaped by gravity.', -28, -18, '#fff4dc'],
      ['titan', 'Titan Echo', 'Saturn’s moon Titan has thick orange air and lakes of hydrocarbons.', 44, -136, '#ffd39c'],
    ),
    visualKind: 'saturn',
    radius: 3.1,
    orbitRadius: 52.3,
    orbitSpeed: 0.022,
    rotationSpeed: 0.29,
    focusDistance: 12.8,
    atmosphereColor: '#ffe0a9',
    glowColor: '#ffbd6f',
    ringColor: '#f9e1b2',
    hasRings: true,
    moonCount: 2,
    moonScale: 0.14,
    moonOrbitRadius: 5.2,
    axialTilt: 0.47,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    subtitle: 'The sideways ice giant drifting in blue silence',
    prompt: 'Track three pale beacons across Uranus’s tilted glow and dim ring shadow.',
    question: 'What makes Uranus especially unusual to observe?',
    answer: 'It rotates tipped almost on its side',
    celebration: 'Axis lock achieved. Uranus rolls through space like a sideways lantern.',
    choices: choices(
      'It rotates tipped almost on its side',
      'It is covered in lava seas',
      'It has no atmosphere at all',
    ),
    hotspots: hotspots(
      ['tilt', 'Axis Beacon', 'Uranus rotates with an extreme tilt, almost rolling around the Sun.', 64, 18, '#c7f6ff'],
      ['haze', 'Methane Haze', 'Methane in the atmosphere helps tint Uranus blue-green.', -8, 114, '#98f1ff'],
      ['shadow', 'Ring Shadow', 'Uranus has faint rings that are much darker than Saturn’s.', 20, -92, '#e6ffff'],
    ),
    visualKind: 'uranus',
    radius: 2.2,
    orbitRadius: 63.7,
    orbitSpeed: 0.014,
    rotationSpeed: 0.16,
    focusDistance: 8.9,
    atmosphereColor: '#9ff1ff',
    glowColor: '#69e3ff',
    ringColor: '#b9f6ff',
    hasRings: true,
    moonCount: 2,
    moonScale: 0.12,
    moonOrbitRadius: 3.7,
    axialTilt: 1.72,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    subtitle: 'A sapphire frontier lashed by supersonic winds',
    prompt: 'Chase three storm beacons through Neptune’s deep blue atmosphere at the edge of the route.',
    question: 'Why can Neptune drive such intense winds even so far from the Sun?',
    answer: 'Its atmosphere is powered by strong internal heat and pressure differences',
    celebration: 'Storm route complete. Neptune closes the voyage in electric blue motion.',
    choices: choices(
      'Its atmosphere is powered by strong internal heat and pressure differences',
      'Sunlight is strongest there',
      'Its rings trap giant fans of air',
    ),
    hotspots: hotspots(
      ['storm', 'Dark Storm Eye', 'Neptune can grow giant dark storms in its upper atmosphere.', -12, 42, '#79b9ff'],
      ['winds', 'Wind Shear Arc', 'Its winds can race faster than those on any other planet.', 24, -132, '#a7d6ff'],
      ['heat', 'Internal Flame', 'Neptune still leaks internal heat, helping energize the atmosphere.', 54, 102, '#dff0ff'],
    ),
    visualKind: 'neptune',
    radius: 2.15,
    orbitRadius: 74.8,
    orbitSpeed: 0.011,
    rotationSpeed: 0.19,
    focusDistance: 8.6,
    atmosphereColor: '#64a7ff',
    glowColor: '#3b86ff',
    moonCount: 1,
    moonScale: 0.15,
    moonOrbitRadius: 3.2,
    axialTilt: 0.52,
  },
]

export function buildMissions(data: unknown): PlanetMission[] {
  return buildMissionList(DEFAULT_MISSIONS, data)
}

export const DEFAULT_INIT_DATA: SolarDefenseInitData = {
  missions: DEFAULT_MISSIONS.map((mission) => ({
    planet: mission.name,
    subtitle: mission.subtitle,
    prompt: mission.prompt,
    clues: mission.hotspots.map((item) => item.clue),
    question: mission.question,
    options: mission.choices.map((choice) => choice.label),
    answer: mission.answer,
    celebration: mission.celebration,
  })),
}
